redhat-developer/mapt

Makefile
remove unused generate goal on build target
=> remove unused generate goal on build target

pkg/infra/aws/modules/compute/compute.go, pkg/infra/aws/modules/compute/macm1/macm1.go, pkg/infra/aws/modules/compute/macm1/types.go, pkg/infra/aws/modules/compute/request.go, pkg/infra/aws/modules/compute/rhel/rhel.go, pkg/infra/aws/modules/compute/rhel/types.go, pkg/infra/aws/modules/compute/types.go, pkg/infra/aws/modules/environment/environment.go
This allow to define specific ingress rules for SG linked to compute
=> added custom ingress rules for computes

.gitignore, README.md, cmd/cmd/ami-replicas-create.go, cmd/cmd/ami-replicas-destroy.go, cmd/cmd/ami-replicas.go, cmd/cmd/constants.go, hacks/packer/README.md, hacks/packer/build.sh, hacks/packer/images/Dockerfile, hacks/packer/windows/ami.pkr.hcl, hacks/packer/windows/misc.txt, hacks/packer/windows/setup.ps1, hacks/packer/windows/ud_winrm_English.ps1, hacks/packer/windows/ud_winrm_Spanish.ps1, images/entrypoint.sh, pkg/infra/aws/modules/ami/ami.go, pkg/infra/aws/modules/ami/api.go, pkg/infra/aws/modules/ami/types.go, pkg/infra/aws/modules/compute/host/macm1/macm1.go, pkg/infra/aws/modules/compute/host/rhel/rhel.go, pkg/infra/aws/modules/compute/host/windows/userdata.go, pkg/infra/aws/modules/compute/host/windows/windows.go, pkg/infra/aws/modules/compute/request.go, pkg/infra/aws/modules/compute/services/snc/snc.go, pkg/infra/aws/modules/compute/types.go, pkg/infra/aws/support-matrix/matrix.go
The idea is to build custom images for supported host to improve the time to spin the machines. 
Ex. setup all windows customizations for the machine: autologin, ssh, ...
Fix #30
=> Add custom image support for windows supported hosts

cmd/cmd/ami-replicas-create.go, cmd/cmd/ami-replicas-destroy.go, pkg/infra/aws/modules/ami-replication/ami.go, pkg/infra/aws/modules/ami-replication/api.go, pkg/infra/aws/modules/ami-replication/types.go, pkg/infra/aws/modules/ami/types.go, pkg/infra/aws/modules/compute/request.go, pkg/infra/aws/modules/compute/types.go, pkg/infra/aws/modules/environment/api.go, pkg/infra/aws/modules/environment/environment.go, pkg/infra/aws/modules/environment/types.go, pkg/infra/aws/modules/network/constants.go, pkg/infra/aws/modules/network/network.go, pkg/infra/aws/modules/network/types.go, pkg/infra/aws/support-matrix/constants.go, pkg/infra/aws/support-matrix/matrix.go, pkg/infra/aws/support-matrix/types.go
=> replicate custom amis

pkg/provider/azure/action/windows/rhqp-ci-setup.ps1
=> Remove curl alias on PS profile

Makefile, tkn/infra-management-aws.yaml, tkn/infra-management-azure.yaml
=> Credentials as optional within workspaces feature from tekton

pkg/provider/aws/action/fedora/fedora.go, pkg/provider/aws/action/rhel/rhel.go, pkg/provider/aws/action/windows/windows.go, pkg/provider/aws/modules/ec2/compute/compute.go
=> fix: Fix #157

tkn/infra-aws-rhel.yaml
=> rh-account-secret workspace marked as optional on infra-aws-rhel

README.md
=> add features on README file

tkn/infra-aws-fedora.yaml, tkn/infra-aws-mac.yaml, tkn/infra-aws-rhel.yaml, tkn/infra-aws-windows-server.yaml, tkn/infra-azure-windows-desktop.yaml
=> chore: increase limits for tekton tasks

hacks/aws_setup.sh
Should fix at least two of 3 issues mentioned in #180.
=> Fix a aws-setup script

pkg/manager/manager.go, pkg/provider/aws/action/fedora/fedora.go, pkg/provider/aws/action/mac/mac-dh.go, pkg/provider/aws/action/mac/mac-machine.go, pkg/provider/aws/action/rhel/rhel.go, pkg/provider/aws/action/windows/windows.go, pkg/provider/aws/modules/ami/ami.go, pkg/provider/azure/action/windows/windows.go
=> fix: #182 now program exists with 1 in case pulumi executions fails

pkg/provider/util/command/command.go
=> https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2048522

tkn/infra-azure-windows-desktop.yaml
fix: if syntax on tekton azure windows desktop
=> fix: if syntax on tekton azure windows desktop

pkg/provider/azure/action/windows/rhqp-ci-setup.ps1
=> chore: uninstall Onedrive for testing windows desktop machines

pkg/provider/aws/data/ami.go
=> fix: aws windows ami not found is copied to target region

pkg/provider/aws/action/windows/bootstrap.ps1
=> Windows aws machine force reboot after bootstrap script.

tkn/infra-aws-rhel.yaml
=> fix: missing arch param for infra aws rhel. Fix #243

cmd/cmd/aws/hosts/rhel.go, pkg/provider/aws/action/rhel/rhel.go
=> chore: added vm-types as optional param in case we want some specific set of VMs

tkn/infra-aws-rhel.yaml
=> chore: added vm-types param to AWS RHEL tekton task. 

tkn/infra-aws-rhel.yaml
This reverts commit 196da87857952d3bc6410308717627bbff657f0d.
=> Revert "chore: added vm-types param to AWS RHEL tekton task. Fix #247"

cmd/mapt/cmd/aws/hosts/fedora.go, pkg/provider/aws/action/fedora/cloud-config-base, pkg/provider/aws/action/fedora/fedora.go
=> feat: add gh actions runner setup for fedora on aws

Makefile, README.md, cmd/mapt/cmd/aws/hosts/fedora.go, tkn/infra-aws-fedora.yaml, tkn/infra-aws-mac.yaml, tkn/infra-aws-rhel.yaml, tkn/infra-aws-windows-server.yaml, tkn/infra-azure-aks.yaml, tkn/infra-azure-fedora.yaml, tkn/infra-azure-rhel.yaml, tkn/infra-azure-windows-desktop.yaml, tkn/template/infra-aws-fedora.yaml, tkn/template/infra-aws-mac.yaml, tkn/template/infra-aws-rhel.yaml, tkn/template/infra-aws-windows-server.yaml, tkn/template/infra-azure-aks.yaml, tkn/template/infra-azure-fedora.yaml, tkn/template/infra-azure-rhel.yaml, tkn/template/infra-azure-windows-desktop.yaml
=> Tekton fix

pkg/provider/aws/action/rhel/cloud-config-snc
=> fix: missing podman pkg for SNC profile on AWS RHEL. 

Makefile
This PR prepare mapt for its next minor version
=> chore: prepare next dev version: 0.8.0-dev

.github/workflows/build-oci.yaml, .github/workflows/push-oci.yml, Makefile, oci/Containerfile
https://github.com/redhat-developer/mapt/issues/311
=> Enable multi-arch build 

Makefile
https://github.com/redhat-developer/mapt/issues/326
=> fix linux suffix of build image name

.github/workflows/push-oci.yml
Cherry-pick 2ab047a0d835e41bd1463d20ef694af750a0cee8
=> Cherry-pick for fix #365 on v0.7

pkg/provider/aws/action/fedora/cloud-config-base
=> configure ntp servers for fedora on aws using cloud-init

README.md, docs/aws.md, docs/aws/fedora.md, docs/aws/mac.md, docs/aws/rhel.md, docs/aws/windows.md, docs/azure/aks.md, docs/azure/fedora.md, docs/azure/rhel.md, docs/azure/ubuntu.md, docs/azure/windows.md, docs/instance-selection.md, docs/self-hosted-runner.md, docs/serverless-mode.md
Corrected several typos in the README and docs/ markdown files.
=> docs : fix typos in README and other files in `docs/`

pkg/provider/aws/modules/serverless/serverless.go
=> fix: sch role policy retain on delete after first creation. Fix #411.

pkg/provider/azure/action/linux/linux.go
=> fix: userdata on Azure Linux machines

Makefile, tkn/infra-aws-fedora.yaml, tkn/infra-aws-mac.yaml, tkn/infra-aws-rhel.yaml, tkn/infra-aws-windows-server.yaml, tkn/infra-azure-aks.yaml, tkn/infra-azure-fedora.yaml, tkn/infra-azure-rhel.yaml, tkn/infra-azure-windows-desktop.yaml
Signed-off-by: Adrian Riobo <ariobolo@redhat.com>
=> chore: bump v0.8.3-dev

pkg/provider/util/instancetypes/azure.go
fix https://github.com/redhat-developer/mapt/issues/456
=> filter the vmsizes that has lowered vCPU

Makefile, cmd/mapt/cmd/aws/aws.go, cmd/mapt/cmd/aws/services/kind.go, cmd/mapt/cmd/constants/constants.go, pkg/manager/context/context.go, pkg/manager/manager.go, pkg/provider/aws/action/kind/constants.go, pkg/provider/aws/action/kind/kind.go, pkg/provider/aws/action/openshift-snc/constants.go, pkg/provider/aws/aws.go, pkg/provider/aws/modules/allocation/allocation.go, pkg/provider/aws/services/ec2/keypair/keypair.go, pkg/provider/aws/services/s3/s3.go, pkg/util/cloud-config/fedora/cloud-config, pkg/util/cloud-config/fedora/fedora.go, pkg/util/cloud-config/kind/cloud-config, pkg/util/cloud-config/kind/kind.go, tkn/infra-aws-kind.yaml, tkn/template/infra-aws-kind.yaml
Fix #462 
This is based on #455 to reuse some refactoring
=> feat: Add kind as a service 

pkg/provider/aws/constants/constants.go, pkg/provider/aws/modules/ec2/compute/compute.go
Fixes https://github.com/redhat-developer/mapt/issues/515
=> feat: Expand tags to ec2 resources

pkg/provider/aws/action/openshift-snc/cloud-config
=> Adding growpart to snc cloud cloudconfig init

cmd/mapt/cmd/aws/hosts/rhelai.go, pkg/provider/aws/action/rhel-ai/constants.go
This commit fixes couple of minor issues within rhel-ai offering; it fixes the user name for rhel-ai ami to cloud-user and added the force-destroy flag for destroy operation for rhel-ai
=> fix: rhelai minor fixes

tkn/infra-aws-fedora.yaml, tkn/infra-aws-rhel.yaml, tkn/infra-azure-fedora.yaml, tkn/infra-azure-rhel.yaml, tkn/template/infra-aws-fedora.yaml, tkn/template/infra-aws-rhel.yaml, tkn/template/infra-azure-fedora.yaml, tkn/template/infra-azure-rhel.yaml
* Missing parameters added
* Non-existing parameters removed
* Scripts unified
* Formatting fixed and unified
RHEL on AWS tested ✅
=> fix: Parameters of Tekton tasks synced
