redhat-developer/mapt

- pkg/provider/aws/modules/compute/services/snc/userdata.tpl
within new OCP versions it is required to run SNC on a RHEL-9.X based system. For RHEL-9.X there are some libvirt depdencies missing. When cloud-init is trying to install missing dependecies it ends up on error as so the host health checker.
> fix snc host libvirt dependecies for RHEL-9.X

- pkg/provider/azure/action/windows/windows.go
Every resource on the provider should be tagged, recently there was added an option to set custom tags, in addition to them some common ones related to the qenvs run are always added. On that PR the tags were missed on the resource group. This PR add them to the resource group.
> Add tags to resourge group on azure windows action

- oci/Containerfile
> Fix FROM format on Containerfile

- README.md
- cmd/mapt/cmd/aws/hosts/constans.go
- cmd/mapt/cmd/aws/hosts/fedora.go
- cmd/mapt/cmd/aws/hosts/rhel.go
- docs/aws/fedora.md
- pkg/provider/aws/action/fedora/constants.go
- pkg/provider/aws/action/fedora/fedora.go
> feat: Fedora arm64 support. 

- Makefile
- cmd/mapt/cmd/aws/hosts/mac.go
- pkg/provider/aws/action/mac/bootstrap.sh
- pkg/provider/aws/action/mac/mac-machine.go
- pkg/provider/aws/action/mac/types.go
- pkg/util/ghactions/runner.go
this adds new flags to the command `mapt aws mac request` to to install github actions runner on the provisioned instance
it also adds the additional flags to get the various values needed to setup the github actions runner
> feat: add gh actions runner setup for mac on aws

- tkn/infra-aws-fedora.yaml
- tkn/infra-aws-mac.yaml
- tkn/infra-aws-rhel.yaml
- tkn/infra-aws-windows-server.yaml
- tkn/infra-azure-rhel.yaml
- tkn/infra-azure-windows-desktop.yaml
https://github.com/redhat-developer/mapt/issues/254
> add tag parameter on tekton task

- pkg/provider/aws/action/rhel/cloud-config-snc
> Fix delay issues on libvirt service when using RHEL with snc profile

- .github/workflows/build-oci.yaml
- .github/workflows/push-oci.yml
This PR will allow to push images built from PRs to ghcr, this will help testing them out, specially if those are adding features required on other projects.
> chore: push mapt pr images to ghcr registry

- pkg/provider/aws/action/fedora/fedora.go
- pkg/provider/aws/action/rhel/rhel.go
- pkg/provider/aws/data/instance-type.go
- pkg/provider/aws/modules/network/network.go
> Minor fixes around spot and airgap 

- pkg/provider/aws/action/fedora/constants.go
This commit update the regex expresison used to get the official Fedora AMIs on AWS
Fix #321
> fix: Fedora ami name regex is no longer valid. 

- cmd/mapt/cmd/aws/hosts/fedora.go
- cmd/mapt/cmd/aws/hosts/mac.go
- cmd/mapt/cmd/aws/hosts/rhel.go
- cmd/mapt/cmd/aws/hosts/windows.go
- cmd/mapt/cmd/azure/hosts/windows.go
- cmd/mapt/cmd/constants/constants.go
- docs/self-hosted-runner.md
- pkg/util/ghactions/runner.go
> feat: add support for adding labels to self hosted runner 

- .github/workflows/build-oci.yaml
- .github/workflows/build-on-hosted-runner.yaml
- .github/workflows/destroy-hosted-runner.yaml
- .github/workflows/provision-hosted-runner.yaml
> ci: add github actions workflow to test self hosted runner

- pkg/provider/aws/modules/spot/stack.go
with this, we get an error instead of a panic
```
% ./out/mapt aws fedora create --spot --airgap --nested-virt --cpus 6 --memory 16 --project-name aws-mapt-fedora-test --backed-url file:///Users/anath/workspace --conn-details-output /tmp/fedora --tags user=anath
DEBU running 'mapt aws fedora create'
DEBU context initialized for mapt6ca81181
DEBU checking stack spotOption-aws-mapt-fedora-test
ERRO Stack outputs are empty please destroy and re-create
```
fixes #327
> check if stack output map is empty before accessing

- .github/workflows/build-oci.yaml
- .github/workflows/destroy-hosted-runner.yaml
- .github/workflows/provision-hosted-runner.yaml
the output tarball name for `podman save` commands in the build-oci workflows were updated as part of the multi-arch image work and now contains the arch as suffix
> ci: update oci image tarball name in self-hosted runner workflows

- .github/workflows/build-img-ghrunner-test.yaml
- .github/workflows/build-on-hosted-runner.yaml
this workflow uses path filters and runs only when files related to self hosted runner code changes
it then triggers the workflow for the  self hosted runner test, making the workflow run only for file changes in the self hosted runner modules
> ci: build image for self hosted gh runner test

- pkg/provider/azure/action/aks/aks.go
- pkg/provider/azure/action/linux/linux.go
- pkg/provider/azure/action/windows/windows.go
- pkg/provider/azure/azure.go
it is found that the location suggested by the spot calculation sometimes do not support the creation of Resource Groups  which is a requirement for `mapt` in those cases we use a pre-defined location for creating the Resource group
related issue: #313
> check if best spot price location supports resource group

- oci/Containerfile
Previously workdir was / and only root user was able to write there, when running mapt on an ocp cluster with security context enable and non-root user mapt fail as it requires to create some ephemeral files on the current workdir. This commit will create a path on the image with open rights and set it as workdir to allow create the required files.
Fix #350
> fix: default workdir with rights for any user

- .github/workflows/push-oci.yml
This commit fixes an issue where values to push the image were not honoring the build information, also it could be dangerouse mix Makefiles versions one on the build side which may differ from default branch (i.e. PR). The caveat we need to maintain on 2 places the oci-load and oci-push actions (on makefile and gh action).
Fix #365
> fix: gh action push oci use values coming from build action

- .github/workflows/provision-hosted-runner.yaml
The gh worflow for testing the feature was missing the arch suffix, added recently to support multi-arch oci mapt. This commit will match the load of the image and its name used to provision the selfhosted runner
> fix: add suffix to image used to test the self hosted runner

- Makefile
- tkn/infra-aws-fedora.yaml
- tkn/infra-aws-mac.yaml
- tkn/infra-aws-rhel.yaml
- tkn/infra-azure-aks.yaml
- tkn/infra-azure-fedora.yaml
- tkn/infra-azure-rhel.yaml
- tkn/infra-azure-windows-desktop.yaml
- tkn/template/infra-aws-fedora.yaml
- tkn/template/infra-aws-mac.yaml
- tkn/template/infra-aws-rhel.yaml
- tkn/template/infra-aws-windows-server.yaml
- tkn/template/infra-azure-aks.yaml
- tkn/template/infra-azure-fedora.yaml
- tkn/template/infra-azure-rhel.yaml
- tkn/template/infra-azure-windows-desktop.yaml
This PR will include changes on the tekton task specs to run mapt.
Fix #294 
Fix #329
> WIP: Mapt Konflux Compliant

- .github/workflows/build-oci.yaml
- .github/workflows/push-oci-pr.yml
- Makefile
~⚠️ This is still work in progress. I haven't verified that behavior is still same as single target yet.~
Related to #364
Split oci-build Makefile target into different targets for handling amd64 and arm64 platforms separately.
Use a separate github action workflow to invoke separated Makefile targets to create container images
> ci : Move arm64 platform image build to a separate github workflow

- pkg/provider/azure/action/linux/linux.go
This is a regression of d37ee99592144b2edb900e1c0742b1a6efb0852d we need to check if a specific type of Linux has a function defined to get the user data. Fix #425
> fix: userdata on Azure Linux machines check if function is nil

- oci/Containerfile
This commit fixed a regression introduced by renovate update PR. Now the builder image is set to fedora 41
Signed-off-by: Adrian Riobo <ariobolo@redhat.com>
> fix: Containerfile wrong shasum for builder image.

- .github/workflows/build-oci.yaml
- .github/workflows/push-oci-pr.yml
When cherry-picking commits to 0.8 branch we missed conflicts on the gh action files. This commit solves the missing conflicts
Signed-off-by: Adrian Riobo <ariobolo@redhat.com>
> fix: gh action missing merge conflict

- .github/workflows/build-oci.yaml
- .github/workflows/push-oci-pr.yml
Fix #418 
Due to split of build amd and arm workflows, push workflow_run is getting triggered multiple times.
+ Add another job that would combine both  image artifacts into one artifact. 
+ In push_pr workflow, add a condition to only execute workflow when both `mapt-amd64.tar` and `mapt-arm64.tar` artifacts are found.
> ci : Add a check in push workflow to only execute when an artifact is present

- .github/workflows/build-img-ghrunner-test.yaml
- .github/workflows/provision-hosted-runner.yaml
Related to https://github.com/redhat-developer/mapt/pull/422#issuecomment-2728497254
Fix failure in `build-img-ghrunner-test` github action due to oci build target split
> ci : fix build-img-ghrunner-test pipeline as per image arch split

- pkg/provider/azure/action/windows/windows.go
- pkg/provider/azure/data/images.go
- pkg/provider/azure/module/virtual-machine/virtual-machine.go
fix https://github.com/redhat-developer/mapt/issues/489
> azure windows sku filter g2 sku

- pkg/provider/aws/action/openshift-snc/constants.go
the ocp-cluster-ca.service after changing the cluster CA writes a new kubeconfig file with updated client certificates for the system:admin user and the token for kubeadmin user, this changes the command  that checked for the status of the ocp-cluster-ca.service to instead check if the kubeconfig file at /opt/crc/kubeconfig is created
fixes #510
> openshift-snc: change command checking if kubeconfig is updated

- cmd/mapt/cmd/aws/services/kind.go
- cmd/mapt/cmd/params/params.go
- pkg/provider/aws/action/kind/kind.go
- pkg/provider/util/cloud-config/kind/cloud-config
- pkg/provider/util/cloud-config/kind/kind.go
- pkg/provider/util/cloud-config/kind/kind_test.go
While testing a konflux running on kind cluster, we found out it'd be good to have additional ports mapped in aws so other services can be publicly accessible (e.g. tekton-results, tekton-pipelines, etc).
This change enables adding extra port mappings via new flag.
Example:
`--extra-port-mappings='[{\"containerPort\": 8080, \"hostPort\": 8080, \"protocol\": \"TCP\"}]'`
Ran the `mapt create` command with following param:
```
--extra-port-mappings='[{"containerPort": 30012, "hostPort": 8080, "protocol": "TCP"}, {"containerPort": 30013, "hostPort": 9000, "protocol": "TCP"}]'
```
And verified that the new ports appear in the EC2 inbound rules
and that the endpoints are accessible via exposed ports
> feat: extra port mapping for kind cluster

- pkg/provider/aws/data/ami.go
This commit includes the Executable users (self) as part of the args when retriving AMIs, this will ensure shared AMIs can be used
Fixes #604
> chore: Allow AWS Shared AMIs at org level

- pkg/provider/aws/action/openshift-snc/constants.go
- pkg/provider/aws/action/openshift-snc/openshift-snc.go
```
INFO  +  command:remote:Command main-ssh-readiness-aos-cmd creating (15s) Dial 1/inf failed: retrying
INFO @ updating..................
INFO  +  command:remote:Command main-ssh-readiness-aos-cmd creating (30s) Dial 2/inf failed: retrying
INFO @ updating...................
INFO  +  command:remote:Command main-ssh-readiness-aos-cmd creating (45s) Dial 3/inf failed: retrying
INFO @ updating..................
INFO  +  command:remote:Command main-ssh-readiness-aos-cmd creating (60s) Dial 4/inf failed: retrying
INFO @ updating..........
INFO  +  command:remote:Command main-ssh-readiness-aos-cmd creating (67s) SSH connectivity established
INFO  +  command:remote:Command main-ssh-readiness-aos-cmd created (67s) SSH connectivity established
INFO  +  command:remote:Command …
```
> openshift-snc: check for SSH readiness before checking for OCP

- tkn/infra-aws-fedora.yaml
- tkn/infra-aws-rhel.yaml
- tkn/infra-azure-fedora.yaml
- tkn/infra-azure-rhel.yaml
- tkn/template/infra-aws-fedora.yaml
- tkn/template/infra-aws-rhel.yaml
- tkn/template/infra-azure-fedora.yaml
- tkn/template/infra-azure-rhel.yaml
* params with default value of empty string are not evaluated correctly
It used to render script like this
```
if [[ create == "create" ]]; then
cmd+="--conn-details-output /opt/host-info "
if [[  != "" ]]; then         # notice left-hand operand missing, bash syntax error
cmd+="--compute-sizes  "    # empty-string value not rendered which breaks mapt
else
```
> fix: unify quotes to avoid bash syntax errors with empty strings

- go.mod
- pkg/manager/context/context.go
- pkg/provider/aws/aws.go
- pkg/provider/aws/data/regions.go
- pkg/provider/aws/data/spot.go
- pkg/provider/aws/modules/allocation/allocation.go
- pkg/provider/azure/azure.go
- tools/go.mod
When backed url is used with a s3 bucket we need to change the region to match the bucket region, then the original target region was never set it back, causing to always use the bucket region to deploy non spot instances. This commit will set it back. 
Fixes #614 
Fixes #617
> fix: aws wrong target region on non-spot instances

- tkn/infra-aws-fedora.yaml
- tkn/infra-aws-kind.yaml
- tkn/infra-aws-mac.yaml
- tkn/infra-aws-ocp-snc.yaml
- tkn/infra-aws-rhel.yaml
- tkn/infra-aws-windows-server.yaml
- tkn/infra-azure-aks.yaml
- tkn/infra-azure-fedora.yaml
- tkn/infra-azure-rhel.yaml
- tkn/infra-azure-windows-desktop.yaml
- tkn/template/infra-aws-fedora.yaml
- tkn/template/infra-aws-kind.yaml
- tkn/template/infra-aws-mac.yaml
- tkn/template/infra-aws-ocp-snc.yaml
- tkn/template/infra-aws-rhel.yaml
- tkn/template/infra-aws-windows-server.yaml
- tkn/template/infra-azure-aks.yaml
- tkn/template/infra-azure-fedora.yaml
- tkn/template/infra-azure-rhel.yaml
- tkn/template/infra-azure-windows-desktop.yaml
Previously when debug mode was active, AWS credentials were displayed which is very insecure because Tekton logs could be archived for long time.
Now only the first and last character of sensitive credentials are displayed.
> Mask AWS and Azure credentials in debug mode
